FROM snakepacker/python:all

RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install -y build-essential ruby ruby-dev make libffi-dev \
    devscripts python3.8-dev git
RUN gem install ruby-xz -v 0.2.3 --no-rdoc --no-ri
RUN gem install fpm --no-rdoc --no-ri
RUN python3.8 -m venv /home/env
RUN /home/env/bin/pip install -U virtualenv sh plumbum pip
RUN apt-get autoremove -y
RUN apt-get clean all