FROM ubuntu:xenial

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y gnupg2 && \
    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6A755776 && \
    apt-get purge -y gnupg2 && \
    echo "deb http://ppa.launchpad.net/deadsnakes/ppa/ubuntu xenial main" | tee -a /etc/apt/sources.list.d/deadsnakes.list && \
    apt-get update && \
    apt-get install -y python3.7-minimal libpython3.7-stdlib python3.7-distutils python3.7-venv \
        build-essential ruby ruby-dev make libffi-dev devscripts python3.7-dev git virtualenv && \
    apt-get autoremove -y && \
    apt-get clean all && \
    rm -fr /var/lib/apt/lists /var/lib/cache/* /var/log/*

RUN gem install ruby-xz -v 0.2.3 --no-rdoc --no-ri
RUN gem install fpm --no-rdoc --no-ri
ADD https://bootstrap.pypa.io/get-pip.py /usr/share/python/get-pip.py
RUN /usr/bin/python3.7 -m venv /home/env
RUN /usr/bin/python3.7 /usr/share/python/get-pip.py
RUN /home/env/bin/pip install -U virtualenv sh plumbum pip
